# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - name: Set version from git tag
        run: yarn version --no-git-tag-version --new-version ${GITHUB_REF#refs/tags/}
      - run: yarn build
      - run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ env.ACT }}
        run: apt-get update && apt-get install -y git rsync
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn build-docs
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: docs
          folder: docs
          token: ${{ secrets.GITHUB_TOKEN }}
